# ---- Twitch application ----
[twitch.app]
client_id     = "your_client_id"
client_secret = "your_client_secret"

# ---- Bot identity ----
[twitch.bot]
login = "your_bot_login"           # lowercase
# control_channel = "somechannel"  # optional; defaults to login

# ---- OAuth tokens (user access token flow) ----
[twitch.auth]
access_token  = "user_access_token_without_oauth_prefix"
refresh_token = "refresh_token_for_that_user_access_token"